apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-{environment}
  namespace: {environment}
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-pv-{environment}"
